import React from 'react';
import { Alert, Image, Linking, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useApp } from '../store';
import { colors, shadow } from '../theme';

export function ProfileScreen() {
  const { contributions, fuelPoints, saved, notificationsEnabled, setNotificationsEnabled, usingDeviceLocation, setTab } = useApp();
  return <View style={styles.screen}><View style={styles.header}><Text style={styles.headerTitle}>Profile</Text><Text style={styles.demo}>DEMO ACCOUNT</Text></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.profileCard}><Image source={require('../../mobile-assets/profile.webp')} style={styles.portrait} /><View style={{ flex: 1 }}><Text style={styles.name}>Lagos Driver</Text><Text style={styles.member}>Moniepoint PMS contributor</Text></View><Ionicons name="checkmark-circle" size={21} color={colors.blue} /></View>
    <View style={styles.stats}><View style={styles.stat}><Ionicons name="document-text-outline" size={22} color={colors.blue} /><Text style={styles.statValue}>{contributions}</Text><Text style={styles.statLabel}>Contributions</Text></View><View style={styles.stat}><Ionicons name="star-outline" size={22} color="#B88600" /><Text style={styles.statValue}>{fuelPoints}</Text><Text style={styles.statLabel}>Fuel Points</Text></View><View style={styles.stat}><Ionicons name="bookmark-outline" size={22} color={colors.blue} /><Text style={styles.statValue}>{saved.length}</Text><Text style={styles.statLabel}>Saved</Text></View></View>
    <Text style={styles.sectionTitle}>Your app</Text><View style={styles.settings}><Setting icon="bookmark-outline" title="Saved stations" subtitle={`${saved.length} favourites`} onPress={() => setTab('Saved')} /><View style={styles.divider} /><View style={styles.settingRow}><View style={styles.settingIcon}><Ionicons name="notifications-outline" size={20} color={colors.blue} /></View><View style={{ flex: 1 }}><Text style={styles.settingTitle}>Notifications</Text><Text style={styles.settingSub}>Demo preference</Text></View><Switch value={notificationsEnabled} onValueChange={setNotificationsEnabled} trackColor={{ false: '#CBD5E1', true: '#9DC0FF' }} thumbColor={notificationsEnabled ? colors.blue : colors.white} accessibilityLabel="Notifications" /></View><View style={styles.divider} /><Setting icon="location-outline" title="Location permission" subtitle={usingDeviceLocation ? 'Using your location' : 'Using Victoria Island demo location'} onPress={() => Linking.openSettings()} /></View>
    <Text style={styles.sectionTitle}>More</Text><View style={styles.settings}><Setting icon="settings-outline" title="App settings" subtitle="Location and notifications" onPress={() => Linking.openSettings()} /><View style={styles.divider} /><Setting icon="information-circle-outline" title="About this demo" subtitle="Moniepoint PMS Tracker · 1.0.0" onPress={() => Alert.alert('About Moniepoint PMS Tracker', 'A Lagos fuel price discovery prototype. All station prices, statuses, rewards, and reports are local demo data. Confirm prices at the pump.')} /></View>
    <View style={styles.note}><Ionicons name="shield-checkmark-outline" size={18} color={colors.blue} /><Text style={styles.noteText}>Reports and saved stations are kept on this device. There is no live price backend in this demo.</Text></View>
  </ScrollView></View>;
}

function Setting({ icon, title, subtitle, onPress }: { icon: keyof typeof Ionicons.glyphMap; title: string; subtitle: string; onPress: () => void }) {
  return <Pressable onPress={onPress} style={styles.settingRow}><View style={styles.settingIcon}><Ionicons name={icon} size={20} color={colors.blue} /></View><View style={{ flex: 1 }}><Text style={styles.settingTitle}>{title}</Text><Text style={styles.settingSub}>{subtitle}</Text></View><Ionicons name="chevron-forward" size={17} color={colors.slate} /></Pressable>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background }, header: { height: 66, paddingHorizontal: 17, backgroundColor: colors.white, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, headerTitle: { color: colors.navy, fontSize: 21, fontWeight: '800' }, demo: { color: colors.blue, fontSize: 10, fontWeight: '800' }, content: { padding: 16, paddingBottom: 30 }, profileCard: { backgroundColor: colors.white, borderRadius: 18, padding: 15, flexDirection: 'row', alignItems: 'center', gap: 12, ...shadow }, portrait: { width: 58, height: 58, borderRadius: 29 }, name: { color: colors.navy, fontSize: 17, fontWeight: '800' }, member: { color: colors.slate, fontSize: 11, marginTop: 3 }, stats: { flexDirection: 'row', gap: 8, marginTop: 12 }, stat: { flex: 1, minHeight: 97, borderRadius: 15, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center', gap: 3 }, statValue: { color: colors.navy, fontSize: 20, fontWeight: '900' }, statLabel: { color: colors.slate, fontSize: 10, textAlign: 'center' }, sectionTitle: { color: colors.navy, fontSize: 17, fontWeight: '800', marginTop: 24, marginBottom: 9 }, settings: { backgroundColor: colors.white, borderRadius: 16, paddingHorizontal: 13 }, settingRow: { minHeight: 65, flexDirection: 'row', alignItems: 'center', gap: 11 }, settingIcon: { width: 34, height: 34, backgroundColor: colors.paleBlue, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, settingTitle: { color: colors.navy, fontSize: 13, fontWeight: '700' }, settingSub: { color: colors.slate, fontSize: 10, marginTop: 3 }, divider: { height: 1, backgroundColor: colors.border, marginLeft: 45 }, note: { backgroundColor: '#E7F0FF', borderRadius: 14, padding: 12, flexDirection: 'row', gap: 9, marginTop: 18 }, noteText: { color: colors.slate, fontSize: 10, lineHeight: 15, flex: 1 },
});
