import React, { useEffect, useState } from 'react';
import { Alert, FlatList, Image, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import * as ImagePicker from 'expo-image-picker';
import { Ionicons } from '@expo/vector-icons';
import type { Availability, QueueStatus } from '../models';
import { relativeTime } from '../models';
import { useApp } from '../store';
import { colors, shadow } from '../theme';

const prices = [680, 690, 695, 700, 710];
const availabilityOptions: { value: Availability; title: string; subtitle: string; icon: keyof typeof Ionicons.glyphMap }[] = [
  { value: 'selling', title: 'Selling Now', subtitle: 'Pumps open', icon: 'checkmark-circle-outline' },
  { value: 'unavailable', title: 'Out of Fuel', subtitle: 'Station dry', icon: 'close-circle-outline' },
  { value: 'restocking', title: 'Tanker In', subtitle: 'Restocking', icon: 'hourglass-outline' },
];
const queueOptions: { value: QueueStatus; title: string; subtitle: string; color: string }[] = [
  { value: 'low', title: '< 5 min', subtitle: 'Fast moving', color: colors.green },
  { value: 'moderate', title: '15–20 min', subtitle: 'Moderate', color: '#D6A600' },
  { value: 'heavy', title: '35+ min', subtitle: 'Long wait', color: colors.red },
];

export function ReportScreen() {
  const insets = useSafeAreaInsets();
  const { stations, selectedId, select, submit, setTab, setDetailsOpen, fuelPoints } = useApp();
  const station = stations.find(item => item.id === selectedId) ?? stations[0];
  const [price, setPrice] = useState(String(station?.pmsPrice ?? 695));
  const [availability, setAvailability] = useState<Availability>('selling');
  const [queue, setQueue] = useState<QueueStatus>('low');
  const [photo, setPhoto] = useState<string | null>(null);
  const [chooserOpen, setChooserOpen] = useState(false);
  const [search, setSearch] = useState('');
  const [success, setSuccess] = useState(false);
  useEffect(() => { if (station) { setPrice(String(station.pmsPrice)); setAvailability(station.availability); setQueue(station.queueStatus); setPhoto(null); } }, [station?.id]);
  const numericPrice = Number(price);
  const valid = Number.isInteger(numericPrice) && numericPrice >= 1 && numericPrice <= 2000;

  function changePrice(delta: number) { setPrice(String(Math.max(1, Math.min(2000, (valid ? numericPrice : station?.pmsPrice ?? 695) + delta)))); }
  function doSubmit() {
    if (!station || !valid) { Alert.alert('Check the price', 'Enter a whole naira amount between ₦1 and ₦2,000.'); return; }
    submit(station.id, numericPrice, availability, queue);
    setSuccess(true);
  }
  async function choosePhoto(source: 'camera' | 'library') {
    try {
      if (source === 'camera') {
        const permission = await ImagePicker.requestCameraPermissionsAsync();
        if (!permission.granted) { Alert.alert('Camera unavailable', 'Allow camera access in Settings to add a photo.'); return; }
      } else {
        const permission = await ImagePicker.requestMediaLibraryPermissionsAsync();
        if (!permission.granted) { Alert.alert('Photos unavailable', 'Allow photo access in Settings to attach an image.'); return; }
      }
      const result = source === 'camera'
        ? await ImagePicker.launchCameraAsync({ mediaTypes: ['images'], quality: 0.7 })
        : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.7 });
      if (!result.canceled && result.assets[0]?.uri) setPhoto(result.assets[0].uri);
    } catch { Alert.alert('Photo unavailable', 'Please try again on a device with a camera or photo library.'); }
  }
  if (!station) return null;

  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
    <View style={styles.header}><Text style={styles.headerTitle}>Report Fuel Price</Text><Text style={styles.headerStep}>STEP 1 OF 1</Text></View>
    <ScrollView showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}>
      <View style={styles.intro}><Text style={styles.eyebrow}>● COMMUNITY CONTRIBUTOR MODE</Text><Text style={styles.title}>Update Fuel Price</Text><Text style={styles.introText}>Help Lagos drivers find fair prices and earn Fuel Points.</Text></View>
      <View style={styles.stationCard}><View style={styles.stationIcon}><Ionicons name="business-outline" size={22} color={colors.blue} /></View><View style={{ flex: 1 }}><Text numberOfLines={1} style={styles.stationName}>{station.name}</Text><Text numberOfLines={1} style={styles.stationAddress}>{station.area} · {station.address}</Text></View><Pressable onPress={() => setChooserOpen(true)} style={styles.changeButton}><Text style={styles.changeText}>Change</Text></Pressable></View>
      <View style={styles.card}><Text style={styles.cardOverline}>PMS CURRENT RATE</Text><View style={styles.priceRow}><Pressable onPress={() => changePrice(-1)} accessibilityLabel="Decrease price" style={styles.adjust}><Ionicons name="remove" size={24} color={colors.navy} /></Pressable><View style={styles.priceCenter}><View style={styles.priceInputRow}><Text style={styles.naira}>₦</Text><TextInput value={price} onChangeText={text => setPrice(text.replace(/[^0-9]/g, '').slice(0, 4))} keyboardType="number-pad" selectTextOnFocus style={styles.priceInput} accessibilityLabel="PMS price in naira" /></View><Text style={styles.perLitre}>per litre</Text></View><Pressable onPress={() => changePrice(1)} accessibilityLabel="Increase price" style={[styles.adjust, styles.adjustPlus]}><Ionicons name="add" size={24} color={colors.white} /></Pressable></View>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.quickPrices}>{prices.map(item => <Pressable key={item} onPress={() => setPrice(String(item))} style={[styles.quickPrice, price === String(item) && styles.quickPriceActive]}><Text style={[styles.quickPriceText, price === String(item) && styles.quickPriceTextActive]}>₦{item}</Text></Pressable>)}</ScrollView>
        <View style={styles.lastPrice}><Ionicons name="time-outline" size={17} color={colors.slate} /><Text style={styles.lastPriceText}>Last listed: ₦{station.pmsPrice} · {relativeTime(station.lastUpdated)}</Text></View>
      </View>
      <View style={styles.card}><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>Fuel Availability</Text><Text style={styles.required}>Required</Text></View><View style={styles.optionRow}>{availabilityOptions.map(item => <Pressable key={item.value} onPress={() => setAvailability(item.value)} style={[styles.option, availability === item.value && styles.optionActive]}><Ionicons name={item.icon} size={22} color={availability === item.value ? colors.white : colors.blue} /><Text style={[styles.optionTitle, availability === item.value && styles.optionTextActive]}>{item.title}</Text><Text style={[styles.optionSub, availability === item.value && styles.optionTextActive]}>{item.subtitle}</Text></Pressable>)}</View></View>
      <View style={styles.card}><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>Current Queue</Text><Text style={styles.required}>Lagos forecourt</Text></View><View style={styles.optionRow}>{queueOptions.map(item => <Pressable key={item.value} onPress={() => setQueue(item.value)} style={[styles.option, queue === item.value && styles.queueActive]}><View style={[styles.queueDot, { backgroundColor: item.color }]} /><Text style={styles.optionTitle}>{item.title}</Text><Text style={styles.optionSub}>{item.subtitle}</Text></Pressable>)}</View></View>
      <View style={styles.card}><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>Verification Photo</Text><Text style={styles.required}>Optional</Text></View><Text style={styles.photoIntro}>Pump meter, price board, or POS slip</Text><Pressable onPress={() => Alert.alert('Add a photo', 'Choose a source', [{ text: 'Camera', onPress: () => choosePhoto('camera') }, { text: 'Photo Library', onPress: () => choosePhoto('library') }, { text: 'Cancel', style: 'cancel' }])} style={styles.photoBox}>{photo ? <><Image source={{ uri: photo }} style={styles.photoPreview} /><Text style={styles.photoAttached}>Photo attached · Tap to change</Text></> : <><View style={styles.cameraCircle}><Ionicons name="camera-outline" size={24} color={colors.blue} /></View><Text style={styles.photoTitle}>Add verification photo</Text><Text style={styles.photoSub}>Take a photo or choose from library</Text></>}</Pressable><Text style={styles.photoNote}>Photo stays on this device in the demo.</Text></View>
      <View style={styles.reward}><View style={styles.rewardIcon}><Ionicons name="star-outline" size={23} color={colors.white} /></View><View style={{ flex: 1 }}><Text style={styles.rewardTitle}>+25 Fuel Points</Text><Text style={styles.rewardSub}>Demo reward · Current balance {fuelPoints}</Text></View></View>
    </ScrollView>
    <View style={styles.footer}><Pressable onPress={doSubmit} style={[styles.submit, !valid && styles.submitDisabled]}><Ionicons name="paper-plane-outline" size={18} color={colors.white} /><Text style={styles.submitText}>Submit Verified Price · ₦{valid ? numericPrice : '—'}</Text></Pressable><Text style={styles.disclaimer}>Demo report stored locally on this device.</Text></View>
    <Modal visible={chooserOpen} animationType="slide" onRequestClose={() => setChooserOpen(false)}><View style={[styles.chooser, { paddingTop: insets.top, paddingBottom: insets.bottom }]}><View style={styles.chooserHeader}><Text style={styles.chooserTitle}>Choose a station</Text><Pressable onPress={() => setChooserOpen(false)} style={styles.close}><Ionicons name="close" size={23} color={colors.navy} /></Pressable></View><TextInput placeholder="Search stations or areas" value={search} onChangeText={setSearch} style={styles.chooserSearch} /><FlatList data={stations.filter(item => `${item.name} ${item.area}`.toLowerCase().includes(search.toLowerCase()))} keyExtractor={item => item.id} renderItem={({ item }) => <Pressable onPress={() => { select(item.id); setChooserOpen(false); setSearch(''); }} style={styles.chooserItem}><Ionicons name="business-outline" size={21} color={colors.blue} /><View style={{ flex: 1 }}><Text style={styles.chooserName}>{item.name}</Text><Text style={styles.chooserArea}>{item.area}</Text></View><Text style={styles.chooserPrice}>₦{item.pmsPrice}</Text></Pressable>} /></View></Modal>
    <Modal visible={success} transparent animationType="fade" onRequestClose={() => setSuccess(false)}><View style={styles.successBackdrop}><View style={styles.successCard}><View style={styles.successIcon}><Ionicons name="checkmark" size={34} color={colors.white} /></View><Text style={styles.successTitle}>Price update saved</Text><Text style={styles.successText}>{station.name} is now listed at ₦{valid ? numericPrice : station.pmsPrice}/L in this demo.</Text><Text style={styles.successPoints}>+25 Fuel Points earned</Text><Pressable onPress={() => { setSuccess(false); setTab('Map'); setDetailsOpen(true); }} style={styles.successButton}><Text style={styles.successButtonText}>View station</Text></Pressable><Pressable onPress={() => { setSuccess(false); setTab('Map'); }} style={styles.doneButton}><Text style={styles.doneText}>Done</Text></Pressable></View></View></Modal>
  </KeyboardAvoidingView>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background }, header: { height: 56, backgroundColor: colors.white, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18 }, headerTitle: { fontSize: 18, color: colors.navy, fontWeight: '800' }, headerStep: { fontSize: 10, color: colors.blue, fontWeight: '800' }, content: { padding: 16, paddingBottom: 24, gap: 14 }, intro: { gap: 5, marginTop: 3 }, eyebrow: { color: colors.blue, fontSize: 10, fontWeight: '800', letterSpacing: 0.5 }, title: { color: colors.navy, fontSize: 27, fontWeight: '900' }, introText: { color: colors.slate, fontSize: 13, lineHeight: 18 },
  stationCard: { minHeight: 73, borderRadius: 16, backgroundColor: '#EFF4FF', padding: 13, flexDirection: 'row', alignItems: 'center', gap: 10 }, stationIcon: { width: 42, height: 42, borderRadius: 11, backgroundColor: '#E0EBFF', alignItems: 'center', justifyContent: 'center' }, stationName: { color: colors.navy, fontSize: 14, fontWeight: '800' }, stationAddress: { color: colors.slate, fontSize: 11, marginTop: 3 }, changeButton: { minWidth: 55, minHeight: 44, justifyContent: 'center', alignItems: 'center' }, changeText: { color: colors.blue, fontSize: 12, fontWeight: '800' },
  card: { backgroundColor: colors.white, borderRadius: 18, padding: 15, ...shadow }, cardOverline: { color: colors.slate, fontSize: 11, fontWeight: '800', letterSpacing: 0.5 }, priceRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12 }, adjust: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.paleBlue, alignItems: 'center', justifyContent: 'center' }, adjustPlus: { backgroundColor: colors.blue }, priceCenter: { alignItems: 'center', minWidth: 120 }, priceInputRow: { flexDirection: 'row', alignItems: 'center' }, naira: { color: colors.blue, fontSize: 27, fontWeight: '900' }, priceInput: { color: colors.navy, fontSize: 32, fontWeight: '900', minWidth: 66, padding: 0, textAlign: 'center' }, perLitre: { color: colors.slate, fontSize: 11 }, quickPrices: { gap: 6, alignItems: 'center', paddingTop: 16, paddingBottom: 3 }, quickPrice: { borderRadius: 15, backgroundColor: '#EFF4FF', paddingHorizontal: 10, paddingVertical: 6 }, quickPriceActive: { backgroundColor: colors.blue }, quickPriceText: { color: colors.navy, fontSize: 11, fontWeight: '700' }, quickPriceTextActive: { color: colors.white }, lastPrice: { backgroundColor: '#EFF4FF', borderRadius: 11, minHeight: 39, flexDirection: 'row', gap: 6, alignItems: 'center', paddingHorizontal: 11, marginTop: 12 }, lastPriceText: { color: colors.slate, fontSize: 11 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 11 }, sectionTitle: { color: colors.navy, fontSize: 15, fontWeight: '800' }, required: { color: colors.slate, fontSize: 10 }, optionRow: { flexDirection: 'row', gap: 6 }, option: { flex: 1, minHeight: 77, borderRadius: 14, backgroundColor: '#EFF4FF', alignItems: 'center', justifyContent: 'center', padding: 5, gap: 2 }, optionActive: { backgroundColor: colors.blue }, queueActive: { backgroundColor: '#DCE9FF' }, optionTitle: { color: colors.navy, fontSize: 11, fontWeight: '800', textAlign: 'center' }, optionSub: { color: colors.slate, fontSize: 9, textAlign: 'center' }, optionTextActive: { color: colors.white }, queueDot: { width: 7, height: 7, borderRadius: 4, marginBottom: 2 },
  photoIntro: { color: colors.slate, fontSize: 11, marginTop: -6, marginBottom: 9 }, photoBox: { minHeight: 116, backgroundColor: '#EFF4FF', borderRadius: 14, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', gap: 4 }, cameraCircle: { width: 43, height: 43, borderRadius: 22, backgroundColor: '#E1EBFF', alignItems: 'center', justifyContent: 'center' }, photoTitle: { color: colors.navy, fontSize: 12, fontWeight: '800' }, photoSub: { color: colors.slate, fontSize: 10 }, photoPreview: { width: '100%', height: 116 }, photoAttached: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: 6, backgroundColor: 'rgba(2,16,45,0.7)', color: colors.white, fontSize: 10, textAlign: 'center' }, photoNote: { color: colors.slate, fontSize: 9, marginTop: 6 },
  reward: { minHeight: 68, borderRadius: 15, backgroundColor: '#DCE6FF', flexDirection: 'row', alignItems: 'center', padding: 13, gap: 10 }, rewardIcon: { width: 39, height: 39, borderRadius: 11, backgroundColor: colors.blue, alignItems: 'center', justifyContent: 'center' }, rewardTitle: { color: colors.navy, fontSize: 14, fontWeight: '800' }, rewardSub: { color: colors.slate, fontSize: 10, marginTop: 3 },
  footer: { padding: 14, backgroundColor: colors.white, borderTopWidth: 1, borderTopColor: colors.border }, submit: { minHeight: 51, borderRadius: 26, backgroundColor: colors.blue, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8 }, submitDisabled: { opacity: 0.45 }, submitText: { color: colors.white, fontSize: 13, fontWeight: '800' }, disclaimer: { textAlign: 'center', color: colors.slate, fontSize: 10, marginTop: 7 },
  chooser: { flex: 1, backgroundColor: colors.background }, chooserHeader: { height: 60, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 17 }, chooserTitle: { color: colors.navy, fontSize: 20, fontWeight: '800', flex: 1 }, close: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, chooserSearch: { height: 47, borderRadius: 12, backgroundColor: colors.white, marginHorizontal: 16, paddingHorizontal: 14, color: colors.navy, marginBottom: 8 }, chooserItem: { minHeight: 65, backgroundColor: colors.white, marginHorizontal: 16, marginTop: 7, borderRadius: 12, flexDirection: 'row', alignItems: 'center', gap: 11, paddingHorizontal: 13 }, chooserName: { color: colors.navy, fontSize: 13, fontWeight: '700' }, chooserArea: { color: colors.slate, fontSize: 10 }, chooserPrice: { color: colors.blue, fontSize: 15, fontWeight: '800' },
  successBackdrop: { flex: 1, backgroundColor: 'rgba(2,16,45,0.45)', alignItems: 'center', justifyContent: 'center', padding: 26 }, successCard: { backgroundColor: colors.white, borderRadius: 24, width: '100%', padding: 22, alignItems: 'center' }, successIcon: { width: 63, height: 63, borderRadius: 32, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center', marginBottom: 14 }, successTitle: { color: colors.navy, fontSize: 21, fontWeight: '900' }, successText: { color: colors.slate, fontSize: 12, textAlign: 'center', lineHeight: 18, marginTop: 8 }, successPoints: { color: colors.blue, fontSize: 12, fontWeight: '800', marginTop: 12 }, successButton: { backgroundColor: colors.blue, borderRadius: 22, height: 44, alignSelf: 'stretch', alignItems: 'center', justifyContent: 'center', marginTop: 17 }, successButtonText: { color: colors.white, fontSize: 13, fontWeight: '800' }, doneButton: { height: 44, justifyContent: 'center' }, doneText: { color: colors.slate, fontSize: 12, fontWeight: '700' },
});
