import React from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { distanceKm, queueLabel, relativeTime, stationImages } from '../models';
import { openDirections } from '../directions';
import { useApp } from '../store';
import { colors, shadow } from '../theme';

export function SavedScreen() {
  const { stations, saved, location, toggleSaved, select, setDetailsOpen, setTab } = useApp();
  const items = stations.filter(item => saved.includes(item.id));
  return <View style={styles.screen}>
    <View style={styles.header}><Text style={styles.headerTitle}>Saved Stations</Text><Text style={styles.headerCount}>{items.length} saved</Text></View>
    {items.length === 0 ? <View style={styles.empty}><View style={styles.emptyIcon}><Ionicons name="bookmark-outline" size={37} color={colors.blue} /></View><Text style={styles.emptyTitle}>Your favourites live here</Text><Text style={styles.emptyText}>Save a station to keep its current demo price, queue, and directions close by.</Text><Pressable onPress={() => setTab('Stations')} style={styles.browse}><Text style={styles.browseText}>Explore stations</Text></Pressable></View> : <ScrollView contentContainerStyle={styles.list} showsVerticalScrollIndicator={false}><Text style={styles.intro}>Quick access to stations you follow</Text>{items.map(item => <View key={item.id} style={styles.card}><Pressable onPress={() => { select(item.id); setDetailsOpen(true); }} style={styles.cardMain}><Image source={stationImages[item.image]} style={styles.image} /><View style={styles.info}><Text numberOfLines={1} style={styles.name}>{item.name}</Text><Text numberOfLines={1} style={styles.address}>{item.area} · {distanceKm(location, item).toFixed(1)} km away</Text><Text style={styles.meta}>{item.availability === 'selling' ? '● Selling now' : '● Check status'} · {queueLabel(item.queueStatus)}</Text><Text style={styles.updated}>Updated {relativeTime(item.lastUpdated)}</Text></View><View style={styles.priceBox}><Text style={styles.price}>₦{item.pmsPrice}</Text><Text style={styles.unit}>/L</Text></View></Pressable><View style={styles.actions}><Pressable onPress={() => toggleSaved(item.id)} accessibilityLabel={`Remove ${item.name} from saved`} style={styles.remove}><Ionicons name="bookmark" size={17} color={colors.blue} /><Text style={styles.removeText}>Saved</Text></Pressable><Pressable onPress={() => openDirections(item)} style={styles.navigate}><Ionicons name="navigate" size={16} color={colors.white} /><Text style={styles.navigateText}>Navigate</Text></Pressable></View></View>)}<Text style={styles.note}>Demo rates can change. Confirm at the pump.</Text></ScrollView>}
  </View>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background }, header: { height: 66, backgroundColor: colors.white, paddingHorizontal: 17, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, headerTitle: { color: colors.navy, fontSize: 21, fontWeight: '800' }, headerCount: { color: colors.blue, fontSize: 11, fontWeight: '800', backgroundColor: colors.paleBlue, overflow: 'hidden', borderRadius: 13, paddingHorizontal: 10, paddingVertical: 6 },
  empty: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 35 }, emptyIcon: { width: 82, height: 82, borderRadius: 41, backgroundColor: colors.paleBlue, alignItems: 'center', justifyContent: 'center' }, emptyTitle: { color: colors.navy, fontSize: 20, fontWeight: '800', marginTop: 18, textAlign: 'center' }, emptyText: { color: colors.slate, fontSize: 13, textAlign: 'center', lineHeight: 20, marginTop: 7 }, browse: { backgroundColor: colors.blue, minHeight: 47, paddingHorizontal: 22, borderRadius: 24, alignItems: 'center', justifyContent: 'center', marginTop: 19 }, browseText: { color: colors.white, fontSize: 13, fontWeight: '800' },
  list: { padding: 16, gap: 12, paddingBottom: 30 }, intro: { color: colors.slate, fontSize: 12, marginBottom: 2 }, card: { backgroundColor: colors.white, borderRadius: 17, overflow: 'hidden', ...shadow }, cardMain: { flexDirection: 'row', minHeight: 116 }, image: { width: 102, height: 116 }, info: { flex: 1, padding: 11, paddingRight: 2 }, name: { color: colors.navy, fontSize: 13, fontWeight: '800' }, address: { color: colors.slate, fontSize: 10, marginTop: 5 }, meta: { color: colors.green, fontSize: 10, fontWeight: '700', marginTop: 8 }, updated: { color: colors.slate, fontSize: 9, marginTop: 5 }, priceBox: { alignItems: 'flex-end', paddingTop: 11, paddingRight: 11 }, price: { color: colors.blue, fontSize: 20, fontWeight: '900' }, unit: { color: colors.slate, fontSize: 10 }, actions: { borderTopWidth: 1, borderTopColor: colors.border, padding: 9, flexDirection: 'row', justifyContent: 'space-between' }, remove: { minHeight: 39, flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 9 }, removeText: { color: colors.blue, fontSize: 11, fontWeight: '700' }, navigate: { minHeight: 39, borderRadius: 20, backgroundColor: colors.blue, paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', gap: 6 }, navigateText: { color: colors.white, fontSize: 11, fontWeight: '800' }, note: { color: colors.slate, fontSize: 10, textAlign: 'center', marginTop: 5 },
});
