import React from 'react';
import { Image, Platform, Pressable, ScrollView, Share, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import MapView, { Marker } from 'react-native-maps';
import Svg, { Polyline as SvgPolyline } from 'react-native-svg';
import { Ionicons } from '@expo/vector-icons';
import { distanceKm, formatPrice, queueLabel, queueWait, relativeTime, stationImages } from '../models';
import { openDirections } from '../directions';
import { useApp } from '../store';
import { colors, shadow } from '../theme';
import { AndroidMap } from '../components/AndroidMap';

export function StationDetailScreen({ stationId, onClose }: { stationId: string; onClose: () => void }) {
  const insets = useSafeAreaInsets();
  const { stations, location, saved, toggleSaved, select, setTab } = useApp();
  const station = stations.find(item => item.id === stationId);
  if (!station) return null;
  const average = Math.round(stations.reduce((sum, item) => sum + item.pmsPrice, 0) / stations.length);
  const savings = Math.max(0, average - station.pmsPrice);
  const distance = distanceKm(location, station);
  const min = Math.min(...station.trend) - 2;
  const max = Math.max(...station.trend) + 2;
  const points = station.trend.map((price, index) => `${8 + index * 47},${56 - ((price - min) / (max - min)) * 45}`).join(' ');
  function report() { if (!station) return; select(station.id); onClose(); setTab('Report'); }
  function share() { if (!station) return; Share.share({ message: `${station.name}, ${station.address}: PMS ₦${formatPrice(station.pmsPrice)}/L. Demo price from Moniepoint PMS Tracker.` }); }

  return <View style={[styles.screen, { paddingTop: insets.top }]}>
    <View style={styles.header}><Pressable onPress={onClose} accessibilityLabel="Close station details" style={styles.headerButton}><Ionicons name="arrow-back" size={23} color={colors.navy} /></Pressable><Text style={styles.headerTitle}>Station Details</Text><Pressable onPress={() => toggleSaved(station.id)} accessibilityLabel="Save station" style={styles.headerButton}><Ionicons name={saved.includes(station.id) ? 'bookmark' : 'bookmark-outline'} size={21} color={colors.blue} /></Pressable><Pressable onPress={share} accessibilityLabel="Share station" style={styles.headerButton}><Ionicons name="share-social-outline" size={21} color={colors.navy} /></Pressable></View>
    <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
      <View style={styles.hero}><Image source={stationImages[station.image]} style={styles.heroImage} /><View style={styles.heroShade} /><View style={styles.openPill}><Text style={styles.openText}>{station.availability === 'selling' ? '●  SELLING NOW' : station.availability === 'restocking' ? '●  RESTOCKING' : '●  OUT OF FUEL'}</Text></View><View style={styles.heroText}><Text style={styles.area}>{station.area.toUpperCase()} · DEMO</Text><Text style={styles.heroName}>{station.name}</Text></View><View style={styles.heroDistance}><Ionicons name="navigate" size={12} color={colors.white} /><Text style={styles.heroDistanceText}>{distance.toFixed(1)} km</Text></View></View>
      <View style={styles.addressRow}><Ionicons name="location-outline" size={16} color={colors.blue} /><Text numberOfLines={1} style={styles.address}>{station.address}, Lagos</Text><Text style={styles.rating}>★ {station.rating.toFixed(1)}</Text></View>
      <View style={styles.pmsCard}><View style={styles.pmsTop}><Text style={styles.pmsLabel}>PMS  Premium Motor Spirit</Text><Text style={styles.livePump}>⚡ Demo rate</Text></View><Text style={styles.pmsPrice}>₦{formatPrice(station.pmsPrice)}<Text style={styles.pmsUnit}>.00 / Litre</Text></Text><View style={styles.verifyBox}><Ionicons name="checkmark-circle" size={21} color={colors.green} /><View style={{ flex: 1 }}><Text style={styles.verifyTitle}>Community verified demo rate</Text><Text style={styles.verifySub}>Last update {relativeTime(station.lastUpdated)} · {station.reportCount} reports</Text></View></View><View style={styles.savings}><Ionicons name="trending-down" size={16} color="#8B6B00" /><Text style={styles.savingsText}>{savings > 0 ? `Save about ₦${formatPrice(savings * 50)} on 50 L vs Lagos average` : 'Compare with other Lagos stations'}</Text></View></View>
      {station.verificationPhotoUri && <View style={styles.proofCard}><View style={styles.proofHead}><Ionicons name="camera-outline" size={18} color={colors.blue} /><Text style={styles.proofTitle}>Latest report photo</Text><Text style={styles.proofNote}>ON THIS DEVICE</Text></View><Image source={{ uri: station.verificationPhotoUri }} style={styles.proofImage} /></View>}
      <View style={styles.fuelRow}><FuelCard title="AGO" subtitle="Automotive Diesel" value={`₦${station.agoPrice.toLocaleString()}`} unit="/L" /><FuelCard title="LPG" subtitle="Cooking Gas (Refill)" value={`₦${station.lpgPrice.toLocaleString()}`} unit="/kg" /></View>
      <Text style={styles.sectionTitle}>Forecourt Conditions</Text><View style={styles.conditions}><Condition icon="speedometer-outline" title={queueLabel(station.queueStatus)} detail={`${station.activePumps} active pumps · ${queueWait(station.queueStatus)} wait`} badge="Crowd updated" /><Condition icon="card-outline" title="Moniepoint POS" detail={station.posAvailable ? 'Available for card and transfer' : 'Reported unavailable'} badge={station.posAvailable ? 'Active' : 'Offline'} /><Condition icon="checkmark-done-outline" title="Pump status" detail="Confirm dispensing at the forecourt" badge="Demo" last /></View>
      <Text style={styles.sectionTitle}>PMS 7-Day Price Trend</Text><View style={styles.chartCard}><View style={styles.chartHeader}><Text style={styles.chartDescription}>{station.trend[0] === station.pmsPrice ? 'Stable this week' : `From ₦${formatPrice(station.trend[0] ?? station.pmsPrice)} to ₦${formatPrice(station.pmsPrice)}`}</Text><Text style={styles.chartBadge}>7 days</Text></View><Svg width="100%" height={65} viewBox="0 0 300 65"><SvgPolyline points={points} fill="none" stroke={colors.blue} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" /></Svg><View style={styles.chartAxis}><Text style={styles.chartAxisText}>6 days ago</Text><Text style={styles.chartAxisText}>Today · ₦{formatPrice(station.pmsPrice)}</Text></View></View>
      <Text style={styles.sectionTitle}>Available Amenities</Text><View style={styles.amenities}>{station.amenities.map(item => <View key={item} style={styles.amenity}><Ionicons name={amenityIcon(item)} size={20} color={colors.blue} /><Text style={styles.amenityText}>{item}</Text></View>)}</View>
      <Text style={styles.sectionTitle}>Location</Text><View style={styles.miniMap}>{Platform.OS === 'android' ? <AndroidMap stations={[station]} selectedId={station.id} center={station} compact /> : <MapView style={StyleSheet.absoluteFill} initialRegion={{ latitude: station.latitude, longitude: station.longitude, latitudeDelta: 0.015, longitudeDelta: 0.015 }} scrollEnabled={false} zoomEnabled={false} rotateEnabled={false} pitchEnabled={false}><Marker coordinate={station} title={station.name} /></MapView>}<View style={styles.mapCaption}><Text style={styles.mapCaptionText}>{station.area} · Lagos</Text><Pressable onPress={() => { onClose(); setTab('Map'); }} style={styles.viewMap}><Text style={styles.viewMapText}>View Map</Text></Pressable></View></View>
    </ScrollView>
    <View style={[styles.footer, { paddingBottom: Math.max(insets.bottom, 12) }]}><Pressable onPress={() => openDirections(station)} style={styles.primary}><Ionicons name="navigate" size={18} color={colors.white} /><Text style={styles.primaryText}>Get Directions · {distance.toFixed(1)} km</Text></Pressable><Pressable onPress={report} style={styles.secondary}><Text style={styles.secondaryText}>Confirm or Report Pump Price</Text><Text style={styles.points}>+25 pts</Text></Pressable></View>
  </View>;
}

function FuelCard({ title, subtitle, value, unit }: { title: string; subtitle: string; value: string; unit: string }) {
  return <View style={styles.fuelCard}><Text style={styles.fuelTitle}>{title}</Text><Text style={styles.fuelSubtitle}>{subtitle}</Text><Text style={styles.fuelValue}>{value}<Text style={styles.fuelUnit}> {unit}</Text></Text><Text style={styles.fuelStock}>✓  Demo price</Text></View>;
}
function Condition({ icon, title, detail, badge, last }: { icon: keyof typeof Ionicons.glyphMap; title: string; detail: string; badge: string; last?: boolean }) {
  return <View style={[styles.condition, !last && styles.conditionBorder]}><View style={styles.conditionIcon}><Ionicons name={icon} size={20} color={colors.blue} /></View><View style={{ flex: 1 }}><Text style={styles.conditionTitle}>{title}</Text><Text style={styles.conditionDetail}>{detail}</Text></View><Text style={styles.conditionBadge}>{badge}</Text></View>;
}
function amenityIcon(item: string): keyof typeof Ionicons.glyphMap {
  const value = item.toLowerCase();
  if (value.includes('atm')) return 'card-outline';
  if (value.includes('air')) return 'speedometer-outline';
  if (value.includes('wash')) return 'water-outline';
  if (value.includes('security')) return 'shield-checkmark-outline';
  if (value.includes('restroom')) return 'body-outline';
  return 'storefront-outline';
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background }, header: { height: 54, backgroundColor: colors.white, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, gap: 5, borderBottomWidth: 1, borderBottomColor: colors.border }, headerButton: { width: 42, height: 44, alignItems: 'center', justifyContent: 'center' }, headerTitle: { color: colors.navy, fontSize: 17, fontWeight: '800', flex: 1, marginLeft: 4 }, content: { padding: 15, paddingBottom: 28 },
  hero: { height: 183, borderRadius: 18, overflow: 'hidden', backgroundColor: colors.paleBlue }, heroImage: { width: '100%', height: '100%' }, heroShade: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, backgroundColor: 'rgba(2,16,45,0.22)' }, openPill: { position: 'absolute', left: 11, top: 11, backgroundColor: colors.white, borderRadius: 16, paddingHorizontal: 10, paddingVertical: 6 }, openText: { color: colors.green, fontSize: 10, fontWeight: '800' }, heroText: { position: 'absolute', bottom: 13, left: 13, right: 80 }, area: { color: colors.white, fontSize: 10, fontWeight: '800' }, heroName: { color: colors.white, fontSize: 19, fontWeight: '800', marginTop: 2 }, heroDistance: { position: 'absolute', bottom: 14, right: 11, flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: colors.blue, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 10 }, heroDistanceText: { color: colors.white, fontSize: 11, fontWeight: '700' },
  addressRow: { height: 41, flexDirection: 'row', alignItems: 'center', gap: 5 }, address: { color: colors.slate, fontSize: 11, flex: 1 }, rating: { color: colors.navy, fontSize: 11, fontWeight: '700' },
  pmsCard: { backgroundColor: '#EAF1FF', borderRadius: 18, padding: 17, ...shadow }, pmsTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 6 }, pmsLabel: { color: colors.navy, fontSize: 12, fontWeight: '700' }, livePump: { color: colors.blue, fontSize: 10, fontWeight: '700' }, pmsPrice: { color: colors.navy, fontSize: 38, fontWeight: '900', marginTop: 12 }, pmsUnit: { fontSize: 13, fontWeight: '500' }, verifyBox: { marginTop: 12, backgroundColor: colors.white, padding: 10, borderRadius: 12, flexDirection: 'row', gap: 8, alignItems: 'center' }, verifyTitle: { color: colors.navy, fontSize: 11, fontWeight: '700' }, verifySub: { color: colors.slate, fontSize: 10, marginTop: 2 }, savings: { marginTop: 10, backgroundColor: '#FFF0C8', borderRadius: 10, padding: 8, flexDirection: 'row', alignItems: 'center', gap: 6 }, savingsText: { color: '#654D00', fontSize: 10, fontWeight: '700', flex: 1 },
  proofCard: { marginTop: 11, backgroundColor: colors.white, borderRadius: 16, padding: 11, gap: 9 }, proofHead: { flexDirection: 'row', alignItems: 'center', gap: 6 }, proofTitle: { color: colors.navy, fontSize: 12, fontWeight: '800', flex: 1 }, proofNote: { color: colors.slate, fontSize: 9, fontWeight: '700' }, proofImage: { width: '100%', height: 180, borderRadius: 10 },
  fuelRow: { flexDirection: 'row', gap: 8, marginTop: 11 }, fuelCard: { flex: 1, backgroundColor: colors.white, padding: 12, borderRadius: 14, borderWidth: 1, borderColor: colors.border }, fuelTitle: { color: colors.blue, fontSize: 10, fontWeight: '800' }, fuelSubtitle: { color: colors.slate, fontSize: 10, marginTop: 5 }, fuelValue: { color: colors.navy, fontSize: 18, fontWeight: '800', marginTop: 4 }, fuelUnit: { color: colors.slate, fontSize: 10, fontWeight: '500' }, fuelStock: { color: colors.blue, fontSize: 10, fontWeight: '700', marginTop: 5 },
  sectionTitle: { color: colors.navy, fontSize: 17, fontWeight: '800', marginTop: 17, marginBottom: 8 }, conditions: { backgroundColor: colors.white, borderRadius: 16, paddingHorizontal: 13 }, condition: { minHeight: 69, flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 10 }, conditionBorder: { borderBottomWidth: 1, borderBottomColor: colors.border }, conditionIcon: { width: 34, height: 34, backgroundColor: colors.paleBlue, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, conditionTitle: { color: colors.navy, fontSize: 11, fontWeight: '700' }, conditionDetail: { color: colors.slate, fontSize: 10, marginTop: 3 }, conditionBadge: { color: colors.blue, fontSize: 9, fontWeight: '700' },
  chartCard: { backgroundColor: colors.white, borderRadius: 16, padding: 14 }, chartHeader: { flexDirection: 'row', justifyContent: 'space-between' }, chartDescription: { color: colors.slate, fontSize: 11 }, chartBadge: { color: colors.blue, backgroundColor: colors.paleBlue, borderRadius: 8, overflow: 'hidden', paddingHorizontal: 6, fontSize: 10 }, chartAxis: { flexDirection: 'row', justifyContent: 'space-between' }, chartAxisText: { color: colors.slate, fontSize: 9 },
  amenities: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, amenity: { width: '31.9%', minHeight: 71, borderRadius: 12, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center', padding: 5, gap: 4 }, amenityText: { color: colors.navy, textAlign: 'center', fontSize: 10, fontWeight: '600' },
  miniMap: { height: 126, borderRadius: 15, overflow: 'hidden', marginBottom: 8 }, mapCaption: { position: 'absolute', left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(2,16,45,0.72)', paddingHorizontal: 10, height: 32, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, mapCaptionText: { color: colors.white, fontSize: 10, fontWeight: '700' }, viewMap: { backgroundColor: colors.white, paddingHorizontal: 9, paddingVertical: 5, borderRadius: 7 }, viewMapText: { color: colors.navy, fontSize: 9, fontWeight: '700' },
  footer: { backgroundColor: colors.white, paddingHorizontal: 15, paddingTop: 10, gap: 7, borderTopWidth: 1, borderTopColor: colors.border }, primary: { height: 47, borderRadius: 24, backgroundColor: colors.blue, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, primaryText: { color: colors.white, fontSize: 13, fontWeight: '800' }, secondary: { height: 40, borderRadius: 20, backgroundColor: colors.background, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 15 }, secondaryText: { color: colors.navy, fontSize: 12, fontWeight: '700' }, points: { color: colors.navy, fontSize: 10, fontWeight: '800', backgroundColor: colors.yellow, paddingHorizontal: 7, paddingVertical: 3, borderRadius: 10, overflow: 'hidden' },
});
